version: "3.9"

services:
  frontend:
    image: thraikal/frontend:latest
    restart: always
    networks:
      nn:
        ipv4_address: 172.18.0.4
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`fl-13-138.zhdk.cloud.switch.ch`) && PathPrefix(`/`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
    depends_on:
      - backend
  backend:
    image: thraikal/backend:latest
    restart: always
    ports:
      - 3001:3001
    networks:
      nn:
        ipv4_address: 172.18.0.3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/ws`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.services.backend.loadbalancer.server.port=3001"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.middlewares.backend.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.backend.headers.customRequestHeaders.Sec-WebSocket-Version=13"
      - "traefik.http.routers.backend.middlewares=backend"
      - "traefik.http.routers.backend.middlewares=backend@docker"
      - "traefik.wss.protocol=https"
    volumes:
      - "./certs:/certs" 
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      nn:
        ipv4_address: 172.18.0.2
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping').ok"]
      interval: 30s
      timeout: 10s
      retries: 5
  traefik:
    image: traefik:v2.5
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik-data:/data"
      - "./traefik-conf:/conf"
      - "./certs:/certs"  # Path to your SSL certificates
    networks:
      nn:
        ipv4_address: 172.18.0.5
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"  # Resolver for Let's Encrypt
      - "--certificatesresolvers.myresolver.acme.email=marc.kalbermatter@students.fhnw.ch"  # Your email here
      - "--certificatesresolvers.myresolver.acme.storage=/certs/acme.json"  # Storage for Let's Encrypt data
volumes:
  mongodb_data:

networks:
  nn:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
